export const MOVIES_API_ADDRESS = "https://api.nomoreparties.co";

//export const MAIN_API_ADDRESS = 'http://localhost:3001';
export const MAIN_API_ADDRESS = 'https://api.zhukirina.nomoredomainswork.ru';

const MEDIUM_SCREEN_WIDTH = 1024;
const MINIMUM_SCREEN_WIDTH = 768;
const VISIBLE_CARDS_MAXIMUM_SCREEN_WIDTH = 12;
const VISIBLE_CARDS_MEDIUM_SCREEN_WIDTH = 8;
const VISIBLE_CARDS_MINIMUM_SCREEN_WIDTH = 5;

export {
  MEDIUM_SCREEN_WIDTH,
  MINIMUM_SCREEN_WIDTH,
  VISIBLE_CARDS_MAXIMUM_SCREEN_WIDTH,
  VISIBLE_CARDS_MEDIUM_SCREEN_WIDTH,
  VISIBLE_CARDS_MINIMUM_SCREEN_WIDTH
}
